source 'https://rubygems.org'

gem 'berkshelf'
gem 'chef'
gem 'chefspec'
gem 'foodcritic'
gem 'guard'
gem 'guard-rubocop'
gem 'kitchen-digitalocean', '~> 0.7.3'
gem 'kitchen-docker'
gem 'kitchen-ec2', '~> 0.8.0'
gem 'kitchen-vagrant'
gem 'test-kitchen'
gem 'winrm-transport', '= 1.0.2'
